movielogger/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^movies/',include('movies.urls',namespace='movies')),
    url(r'^categories/',include('categories.urls',namespace='categories')),
]

movies/urls.py
from django.conf.urls import url
from . import views

app_name = 'movies'

urlpatterns = [
    url(r'^$', views.MovieList.as_view(), name='all'),
    url(r'new/$',views.CreateMovie.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)/$', views.UserMovies.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.MovieDetail.as_view(), name='single'),
    url(r'delete/(?P<pk>\d+)/$', views.DeleteMovie.as_view(), name='delete'),
]

movies/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
# Create your models here.
import misaka
from categories.models import Category

from django.contrib.auth import get_user_model
User = get_user_model()

class Movie(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='movies')
    name = models.TextField()
    name_html = models.TextField(editable = False)
    release = models.DateField(blank=True)
    category = models.ForeignKey(Category, related_name='movies', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.name_html = misaka.html(self.name)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("movies:single", kwargs={"username": self.user.username,'pk':self.pk})
    
    class Meta:
        ordering = ['-release']
        unique_together = ['user', 'name']

movies/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
from django.http import Http404
from django.contrib import messages

from braces.views import SelectRelatedMixin

from . import models
from . import forms
from django.contrib.auth import get_user_model
User = get_user_model()

class MovieList(SelectRelatedMixin,generic.ListView):
    model = models.Movie
    select_related = ('user', 'category')

class UserMovies(generic.ListView):
    model = models.Movie
    template_name = 'movies/user_movie_list.html'

    def get_queryset(self):
        try:
            self.movie_user = User.objects.prefetch_related('movies').get(username__iexact=self.kwargs.get('username'))
            self.movie_watched = models.Category.objects.prefetch_related('movies').get(slug__iexact='watched')
            self.movie_watching = models.Category.objects.prefetch_related('movies').get(slug__iexact='watching')
            self.movie_planned = models.Category.objects.prefetch_related('movies').get(slug__iexact='plan-to-watch')
            
            self.watched=0
            for element in self.movie_user.movies.all():
                if element in self.movie_watched.movies.all():
                    self.watched+=1
            print(self.watched)
            self.watching=0
            for element in self.movie_user.movies.all():
                if element in self.movie_watching.movies.all():
                    self.watching+=1
            print(self.watching)
            self.planned=0
            for element in self.movie_user.movies.all():
                if element in self.movie_planned.movies.all():
                    self.planned+=1
            print(self.planned)

        except User.DoesNotExist:
            raise Http404
        else:
            return self.movie_user.movies.all()
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['movie_user'] = self.movie_user
        return context

class MovieDetail(SelectRelatedMixin ,generic.DetailView):
    model = models.Movie
    select_related = ('user','category')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreateMovie(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('name','category','release')
    model = models.Movie

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeleteMovie(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Movie
    select_related = ('user', 'category')
    success_url = reverse_lazy('movies:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)
    
    def delete(self, *args, **kwargs):
        messages.success(self.request,'Movie Deleted')
        return super().delete(*args, **kwargs)

movies/templates/movies/_movie.html
<div class="movie media">
    <h3><a href="{% url 'movies:single' username=movie.user.username pk=movie.pk %}">{{movie.name_html|safe}}</a></h3>
    <div class="media-body">
        {% comment %} <strong>
            {{post.user.username}}
        </strong> {% endcomment %}
        <h5 class="media-heading">
            
            <span class="username">
                <a href="{% url 'movies:for_user' username=movie.user.username %}">@{{movie.user.username}}</a>
            </span>
            <span>
                <a href="{% url 'categories:single' slug=movie.category.slug %}">{{movie.category}}</a>
            </span>
            <time class="time">
                <a href="{% url 'movies:single' username=movie.user.username pk=movie.pk %}">{{movie.release}}</a>
            </time>
        </h5>
        <div class="media-footer">
            {% if user.is_authenticated and movie.user == user %}
            <a href="{% url 'movies:delete' pk=movie.pk %}" time="delete" class='btn btn-simple'>
                <span class="glyphicon glyphicon-remove text-danger" aria-hidden='true'>
                </span>
                <span class="text-danger icon-label">Delete</span>
            </a>{% endif %}
        </div>
    </div>
</div>

movies/templates/movies/movie_base.html
{% extends 'base.html' %}
{% block content %}
<div class="posts-page">
    <div class="container">
        <div class="row">
            {% block premovie %}{% endblock %}
            {% block movie_content %}{% endblock %}
            {% block post_movie %}{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

movies/templates/movies/movie_confirm_delete.html
{% extends 'movies/movie_base.html' %}

{% block movie_content %}
<h3>Are you sure you want to delete this Movie?</h3>
<div class="posts">
    {% include "movies/_movie.html" with movie=object hide_delete=True %}
</div>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class='btn btn-danger btn-large'>
    <a class='btn btn-simple btn-large btn-default' href="{% url 'movies:single' username=user.username pk=object.pk %}">Cancel</a>
</form>
{% endblock %}

movies/templates/movies/movie_detail.html
{% extends 'movies/movie_base.html' %}
{% block movie_content %}
<div class="col-md-8">
    {% comment %} {% include "movies/_movie.html" %} {% endcomment %}
    <h3>Movie Name - {{movie.name}}</h3>
</div>
{% endblock %}

movies/templates/movies/movie_form.html
{% extends 'movies/movie_base.html' %}
{% load bootstrap3 %}
{% block movie_content %}
<h4>Create a new Movie</h4>
<form id=movieForm action="{% url 'movies:create' %}"  method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Movie" class='btn btn-primary btn-large'>
</form>
{% endblock %}

movies/templates/movies/movie_list.html
{% extends 'movies/movie_base.html' %}
{% block pre_movie_content %}
<div class="col-md-4">
    {% if request.user.is_authenticated %}
    <div class="card card-with-shadow">
        <div class="content">
            <ul class="list-unstyled">
            </ul>
        </div>
    </div>
    {% endif %}
    <div class="card card-with-shadow">
        <div class="content">
            <h5 class="title">All Categories</h5>
            <ul class="list-unstyled">
                {% for other_category in get_other_categories %}
                <li class='group li-with-bullet'><a href="{% url 'categories:single' slug=other_caetgory.slug %}"></a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}


{% block movie_content %}
<div class="col-md-8">
    {% for movie in movie_list %}
    {% if user.is_authenticated and movie.user == user %}
    {% include "movies/_movie.html" %}{% endif %}
    {% endfor %}
</div>
{% endblock %}

movies/templates/movies/user_movie_list.html
{% extends 'movies/movie_base.html' %}

{% block premovie %}
{% if user.is_authenticated and movie_user == user %}
<div class="col-md-4">
    <h1><a href="{% url 'movies:for_user' username=movie_user.username %}">@{{ movie_user.username }}</a>
        </h1>
        <p>written {{ movie_user.movies.count }} movies so far <p>
</div>
{% else %}
<h3>User Not Found</h3>
{% endif %}
{% endblock %}

{% block movie_content %}
{% if user.is_authenticated and movie_user == user %}
<div class="col-md-8">
    {% for movie in movie_list %}
    {% include "movies/_movie.html" %}
    {% endfor %}
</div>{% endif %}
{% endblock %}