accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'signup/$',views.SignUp.as_view(),name='signup'),
]

movielogger/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^movies/',include('movies.urls',namespace='movies')),
    url(r'^categories/',include('categories.urls',namespace='categories')),
]

movies/urls.py
from django.conf.urls import url
from . import views

app_name = 'movies'

urlpatterns = [
    url(r'^$', views.MovieList.as_view(), name='all'),
    url(r'new/$',views.CreateMovie.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)/$', views.UserMovies.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.MovieDetail.as_view(), name='single'),
    url(r'delete/(?P<pk>\d+)/$', views.DeleteMovie.as_view(), name='delete'),
]

templates/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Star Social</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> 

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'movielogger/css/master.css'%}">
</head>
<body>

    <nav class="navbar mynav" role='navigation' id='navbar'>
        <div class="container">
            <a class='navbar-brand mynav' href="{% url 'home' %}">Movie Logger</a>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a href="{% url 'movies:all' %}">All Movies</a></li>
                <li><a href="{% url 'movies:create' %}">Add Movie</a></li>
                <li><a href="{% url 'categories:all' username=user.username %}">Categories</a></li>
                <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container mycontent">
        {% block content %}
        {% endblock %}
    </div>
    
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome to Movie Logger</h1>
<div class="col-md-8">
{% if user.is_authenticated %}
    {% for movie in movie_list %}
    {% if user.is_authenticated and movie.user == user %}
    {% include "movies/_movie.html" %}{% endif %}
    {% endfor %}
{% else %}
<h2>Login Or SignUp to continue</h2>
{% endif %}
</div>
{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% block content %}
<h1>You are logged In!</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<h1>Thanks for visiting, come back soon!</h1>
{% endblock %}